version: '2'

services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: 
      - "/mnt/:/home/pgao/"
      - "./passwd:/etc/pure-ftpd/passwd"
      # - "/folder_on_disk/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: pgao
      # FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/pgao
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: always
